#!/Library/Frameworks/Python.framework/Versions/3.7/bin/python3

import webbrowser,sys,pyperclip

#webbrowser.open("https//www.qq.com")

if len(sys.argv)>1:
    address=''.join(sys.argv[1:])
#else:
    #address=pyperclip.paste()

webbrowser.open('https://www.google.com/maps/place/' + address)
